-- Create note_shares table for sharing notes between users
CREATE TABLE note_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id BIGINT NOT NULL,
    shared_with_user_id BIGINT NOT NULL,
    shared_by_user_id BIGINT NOT NULL,
    permission VARCHAR(20) NOT NULL DEFAULT 'READ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_note_shares_note FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
    CONSTRAINT fk_note_shares_shared_with FOREIGN KEY (shared_with_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_note_shares_shared_by FOREIGN KEY (shared_by_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_note_shares_unique UNIQUE (note_id, shared_with_user_id)
);

-- Create index for efficient queries
CREATE INDEX idx_note_shares_shared_with ON note_shares(shared_with_user_id);
CREATE INDEX idx_note_shares_note ON note_shares(note_id);
